# Generated by Django 5.2 on 2026-04-18 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Thor', '0003_remove_product_time_alter_product_amount_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sale',
            name='product',
        ),
        migrations.AddField(
            model_name='sale',
            name='amount',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sale',
            name='name',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sale',
            name='payment',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sale',
            name='price',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='product',
        ),
    ]
