# Generated by Django 5.2 on 2026-04-18 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Thor', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='amount',
            field=models.IntegerField(verbose_name=100),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.IntegerField(verbose_name=100),
        ),
    ]
